[env]
TERM = "xterm-256color"

[colors.primary]
background = '#121212'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#24292e'
red     = '#C01C28'
green   = '#2EC27E'
yellow  = '#F5C211'
blue    = '#1E78E4'
magenta = '#9841BB'
cyan    = '#0AB9DC'
white   = '#C0BFBC'

# Bright colors
[colors.bright]
black   = '#57606a'
red     = '#ED333B'
green   = '#57E389'
yellow  = '#F8E45C'
blue    = '#51A1FF'
magenta = '#C061CB'
cyan    = '#4FD2FD'
white   = '#F6F5F4'

[font]
size = 13

[font.bold]
family = "IosevkaTerm NFM"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm NFM"
style = "Bold Oblique"

[font.italic]
family = "IosevkaTerm NFM"
style = "Oblique"

[font.normal]
family = "IosevkaTerm NFM"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 5
y = 0
