[env]
TERM = "xterm-256color"

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[colors.normal]
black = "#444444"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[colors.bright]
black = "#666666"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#BCC0CC"

[font]
size = 18

[font.bold]
family = "IosevkaComfyFixed Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaComfyFixed Nerd Font"
style = "Bold Oblique"

[font.italic]
family = "IosevkaComfyFixed Nerd Font"
style = "Oblique"

[font.normal]
family = "IosevkaComfyFixed Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 5
y = 0
