# Colorscheme
[general]
import = [ "./catppuccin-mocha.toml" ]

[env]
TERM = "xterm-256color"

# Theme

[font]
size = 13

[font.bold]
family = "Iosevka Term NFP"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term NFP"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term NFP"
style = "Italic"

[font.normal]
family = "Iosevka Term NFP"
style = "Light"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1

[window.padding]
x = 5
y = 5
