[env]
TERM = "xterm-256color"

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[colors.normal]
# black = "#000000"
# red = "#a60000"
# green = "#006800"
# yellow = "#6f5500"
# blue = "#0031a9"
# magenta = "#721045"
# cyan = "#005e8b"
# white = "#ffffff"
black = "#000000"
red = "#d00000"
green = "#008900"
yellow = "#808000"
blue = "#0000ff"
magenta = "#dd22dd"
cyan = "#008899"
white = "#ffffff"

[colors.bright]
black = "#000000"
red = "#d00000"
green = "#008900"
yellow = "#808000"
blue = "#0000ff"
magenta = "#dd22dd"
cyan = "#008899"
white = "#ffffff"

[font]
size = 18

[font.bold]
family = "IosevkaComfyFixed Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaComfyFixed Nerd Font"
style = "Bold Oblique"

[font.italic]
family = "IosevkaComfyFixed Nerd Font"
style = "Oblique"

[font.normal]
family = "IosevkaComfyFixed Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 5
y = 0
