# -*- conf -*-
# Catppuccin Mocha
# Basically the version of catppuccin that ships with foot in /usr/share/foot/themes/ but with a #000000 background

[colors.primary]
foreground = '#cdd6f4'
# background=1e1e2e
background = '#000000'

[colors.normal]
black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#bac2de'


[colors.bright]
black = '#585b70'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#a6adc8'

[colors.selection]
text = '#cdd6f4'
background = '#414356'

