#! /bin/sh

# general stuff
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
# hsetroot -solid bisque4
~/.fehbg
xsetroot -cursor_name left_ptr
xset r rate 200 30
xset s off -dpms
ibus exit
nm-applet
blueman-applet
export _JAVA_AWT_WM_NONREPARENTING=1

# bar
~/.config/polybar/launch.sh

# workspaces setup
num_monitors="$(xrandr --query | grep ' connected' | wc -l)"
if [num-monitors -eq 1 ]; then
    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
else
    bspc monitor DisplayPort-0 -d 1 2 3 4
    bspc monitor HDMI-A-0 -d 5 6 7
    bspc monitor eDP -d 8 9 10
    bspc wm --reorder-monitors DisplayPort-0 HDMI-A-0 eDP
fi

# looks
bspc config border_width        2
bspc config window_gap          11
bspc config top_padding         35

bspc config focused_border_color "#00bbff"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# for some reason emacsclient frames start floating
# maybe look at the default-frame-alist?
bspc rule -a Emacs:* state=tiled
bspc rule -a Zotero desktop='^8' follow=on
