-- Generated by nwg-displays on 2026-09-14 at 18:57:52. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x403A",
    mode = "1920x1200@60.0",
    position = "0x1599",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "desc:Dell Inc. DELL U2414H 9TG464CU582L",
    mode = "1920x1080@60.0",
    position = "0x519",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "desc:LG Electronics LG HDR 4K 0x000037C5",
    mode = "3840x2160@60.0",
    position = "1920x0",
    scale = 0.9999999999999997,
    vrr = 0
})
