windowrule {
    name = make-resources-floating
    match:class = net.nokyan.Resources
    float = true
}

windowrule {
    name = make-iwgtk-floating
    match:class = org.twosheds.iwgtk
    float = true
}

windowrule {
    name = make-weather-floating
    match:class = org.gnome.Weather
    size = 650 500
    float = true
}

windowrule {
    name = make-pwvucontrol-floating
    match:class = com.saivert.pwvucontrol
    size = 1000 600
    float = true
}

windowrule {
    name = make-blueman-floating
    match:class = blueman-manager
    float = true
}

windowrule {
    name = floating-decorations
    match:float = true
    border_size = 1
}

windowrule {
    name = only-shadow-on-floating
    match:float = false
    no_shadow = on
}
