#!/usr/bin/env bash

max_brightness=$(brightnessctl max)

current_brightness () {
    local cur
    cur=$(brightnessctl get)
    awk -v cur="$cur" \
        -v max="$max_brightness" \
        'BEGIN { printf("%d\n", (cur / max) * 100) }'
}

# string:x-canonical-private-synchronous:osd makes repeated notifications replace each other
notify_brightness() {
    notify-send "Brightness: $(current_brightness)%" \
                -h string:x-canonical-private-synchronous:osd \
                -h int:value:"$(current_brightness)" \
                -e
}

case "$1" in
    up)
        brightnessctl s 2000+
        notify_brightness
        ;;
    down)
        brightnessctl s 2000-
        notify_brightness
        ;;
    *)
        echo "USAGE:"
        echo "  $0 [up/down]"
        ;;
esac
