#!/usr/bin/env bash

last_id_file="/tmp/last_notification_id"

get_last_id() {
    [[ -f "$last_id_file" ]] && cat "$last_id_file" || echo 0
}

save_last_id() {
    echo "$1" > "$last_id_file"
}

max_brightness=$(brightnessctl max)

current_brightness () {
    local cur
    cur=$(brightnessctl get)
    awk -v cur="$cur" \
        -v max="$max_brightness" \
        'BEGIN { printf("%d\n", (cur / max) * 100) }'
}

notify_brightness() {
    local id
    id=$(notify-send "Brightness: $(current_brightness)%" \
                     -h int:value:"$(current_brightness)" \
                     -h string:synchronous:brightness \
                     -r $(get_last_id) \
                     -p)
    save_last_id "$id"
}

case "$1" in
    up)
        brightnessctl s 2000+
        notify_brightness
        ;;
    down)
        brightnessctl s 2000-
        notify_brightness
        ;;
    *)
        echo "USAGE:"
        echo "  $0 [up/down]"
        ;;
esac
