#!/usr/bin/env bash
# find ~/Documents ~/Downloads ~/Desktop ~/Zotero ~/kitcar -type f -name "*.pdf" | fuzzel -d -w 100 -p "  " -a bottom | xargs -I{} zathura {}
find ~/Documents ~/Downloads ~/Desktop ~/Zotero ~/kitcar -type f -name "*.pdf" | vicinae dmenu --placeholder "Open PDF:  " | xargs -I{} zathura {}
