#!/usr/bin/env bash

g=$(slurp) || exit 1
res=$(grim -g "$g" - | tesseract --dpi 120 - stdout)

if [ -n "$res" ] ; then
    printf '%s' "$res" | wl-copy
    notify-send "Copied to clipboard:" "$res"
fi
