#!/usr/bin/env bash

# USAGE: screenshot [-e]
# without -e screenshot to clipboard
# with -e edit in gradia


EDIT=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -e|--edit) EDIT=true ;;
    esac
    shift
done

if [ "$EDIT" = true ]; then
    gradia --screenshot=INTERACTIVE
else
    GEOMETRY=$(slurp)
    if [ -z "$GEOMETRY" ]; then
        exit 1
    fi
    grim -g "$GEOMETRY" - | wl-copy
fi
