plugin {
    hyprbars {
        bar_height = 28
        bar_part_of_window = true
        bar_precedence_over_border = true
        bar_color = rgb(e6e9ef)
        col.text = rgb(4c4f69)
        bar_text_font = SF Pro Display Medium
        bar_text_size = 11
        bar_text_align = center
        bar_button_padding = 8
        bar_padding = 10
        inactive_button_color = rgb(bcc0cc)
        hyprbars-button = rgb(e78284), 10, , hyprctl dispatch killactive
        hyprbars-button = rgb(a6d189), 10, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(8caaee), 10, , hyprctl dispatch togglefloating
    }
}

windowrule {
    name = only-bar-on-floating
    match:float = false
    hyprbars:no_bar = true
}

windowrule {
    name = dim-inactive-bars
    match:focus = false
    hyprbars:bar_color = rgb(eff1f5)
    hyprbars:title_color = rgb(8c8fa1)
}
